name: duanzhixing2016
on:
  workflow_dispatch:
  schedule:
    - cron: '41 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duanzhixing2016
        env:
          klr4: ${{ secrets.klr4 }}
        run: |
          echo $klr4 | jq -r .wzrqb043 | /bin/bash
          echo $mi03537 | jq -r .i69354 | /bin/bash
          echo $k03 | jq -r .kkx72 | /bin/bash
          echo $jijw6263 | jq -r .flkz3014 | /bin/bash
          echo $pkum5 | jq -r .hm6696 | /bin/bash
          echo $rpze79815 | jq -r .m7 | /bin/bash
          echo $vhtln141 | jq -r .n604 | /bin/bash
          echo $t59 | jq -r .r9 | /bin/bash
          echo $woi88725 | jq -r .lhqk65 | /bin/bash

